# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import distributed_gpt_pb2 as distributed__gpt__pb2

GRPC_GENERATED_VERSION = '1.63.0'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in distributed_gpt_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class LeaderStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.giveAgentAssignment = channel.unary_unary(
                '/Leader/giveAgentAssignment',
                request_serializer=distributed__gpt__pb2.AssignmentRequest.SerializeToString,
                response_deserializer=distributed__gpt__pb2.Assignment.FromString,
                _registered_method=True)
        self.giveAgentMessage = channel.unary_unary(
                '/Leader/giveAgentMessage',
                request_serializer=distributed__gpt__pb2.TaskRequest.SerializeToString,
                response_deserializer=distributed__gpt__pb2.Task.FromString,
                _registered_method=True)
        self.processAgentMessage = channel.unary_unary(
                '/Leader/processAgentMessage',
                request_serializer=distributed__gpt__pb2.AgentMessage.SerializeToString,
                response_deserializer=distributed__gpt__pb2.Status.FromString,
                _registered_method=True)


class LeaderServicer(object):
    """Missing associated documentation comment in .proto file."""

    def giveAgentAssignment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def giveAgentMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def processAgentMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LeaderServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'giveAgentAssignment': grpc.unary_unary_rpc_method_handler(
                    servicer.giveAgentAssignment,
                    request_deserializer=distributed__gpt__pb2.AssignmentRequest.FromString,
                    response_serializer=distributed__gpt__pb2.Assignment.SerializeToString,
            ),
            'giveAgentMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.giveAgentMessage,
                    request_deserializer=distributed__gpt__pb2.TaskRequest.FromString,
                    response_serializer=distributed__gpt__pb2.Task.SerializeToString,
            ),
            'processAgentMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.processAgentMessage,
                    request_deserializer=distributed__gpt__pb2.AgentMessage.FromString,
                    response_serializer=distributed__gpt__pb2.Status.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Leader', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Leader(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def giveAgentAssignment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Leader/giveAgentAssignment',
            distributed__gpt__pb2.AssignmentRequest.SerializeToString,
            distributed__gpt__pb2.Assignment.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def giveAgentMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Leader/giveAgentMessage',
            distributed__gpt__pb2.TaskRequest.SerializeToString,
            distributed__gpt__pb2.Task.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def processAgentMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Leader/processAgentMessage',
            distributed__gpt__pb2.AgentMessage.SerializeToString,
            distributed__gpt__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
