# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: distributedGPT.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x64istributedGPT.proto\x12\tmypackage\"3\n\rClientMessage\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"!\n\x0eLeaderResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"3\n\rLeaderMessage\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"!\n\x0e\x43lientResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"*\n\x15RegisterClientRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\")\n\x16RegisterClientResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\x82\x02\n\x0bNodeService\x12L\n\x13SendMessageToLeader\x12\x18.mypackage.ClientMessage\x1a\x19.mypackage.LeaderResponse\"\x00\x12L\n\x13SendMessageToClient\x12\x18.mypackage.ClientMessage\x1a\x19.mypackage.ClientResponse\"\x00\x12W\n\x0eRegisterClient\x12 .mypackage.RegisterClientRequest\x1a!.mypackage.RegisterClientResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'distributedGPT_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CLIENTMESSAGE']._serialized_start=35
  _globals['_CLIENTMESSAGE']._serialized_end=86
  _globals['_LEADERRESPONSE']._serialized_start=88
  _globals['_LEADERRESPONSE']._serialized_end=121
  _globals['_LEADERMESSAGE']._serialized_start=123
  _globals['_LEADERMESSAGE']._serialized_end=174
  _globals['_CLIENTRESPONSE']._serialized_start=176
  _globals['_CLIENTRESPONSE']._serialized_end=209
  _globals['_REGISTERCLIENTREQUEST']._serialized_start=211
  _globals['_REGISTERCLIENTREQUEST']._serialized_end=253
  _globals['_REGISTERCLIENTRESPONSE']._serialized_start=255
  _globals['_REGISTERCLIENTRESPONSE']._serialized_end=296
  _globals['_NODESERVICE']._serialized_start=299
  _globals['_NODESERVICE']._serialized_end=557
# @@protoc_insertion_point(module_scope)
