# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import distributedGPT_pb2 as distributedGPT__pb2

GRPC_GENERATED_VERSION = '1.63.0'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in distributedGPT_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class NodeServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendMessageToLeader = channel.unary_unary(
                '/mypackage.NodeService/SendMessageToLeader',
                request_serializer=distributedGPT__pb2.ClientMessage.SerializeToString,
                response_deserializer=distributedGPT__pb2.LeaderResponse.FromString,
                _registered_method=True)
        self.SendMessageToClient = channel.unary_unary(
                '/mypackage.NodeService/SendMessageToClient',
                request_serializer=distributedGPT__pb2.ClientMessage.SerializeToString,
                response_deserializer=distributedGPT__pb2.ClientResponse.FromString,
                _registered_method=True)
        self.RegisterClient = channel.unary_unary(
                '/mypackage.NodeService/RegisterClient',
                request_serializer=distributedGPT__pb2.RegisterClientRequest.SerializeToString,
                response_deserializer=distributedGPT__pb2.RegisterClientResponse.FromString,
                _registered_method=True)


class NodeServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendMessageToLeader(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendMessageToClient(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterClient(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NodeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendMessageToLeader': grpc.unary_unary_rpc_method_handler(
                    servicer.SendMessageToLeader,
                    request_deserializer=distributedGPT__pb2.ClientMessage.FromString,
                    response_serializer=distributedGPT__pb2.LeaderResponse.SerializeToString,
            ),
            'SendMessageToClient': grpc.unary_unary_rpc_method_handler(
                    servicer.SendMessageToClient,
                    request_deserializer=distributedGPT__pb2.ClientMessage.FromString,
                    response_serializer=distributedGPT__pb2.ClientResponse.SerializeToString,
            ),
            'RegisterClient': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterClient,
                    request_deserializer=distributedGPT__pb2.RegisterClientRequest.FromString,
                    response_serializer=distributedGPT__pb2.RegisterClientResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mypackage.NodeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class NodeService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendMessageToLeader(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mypackage.NodeService/SendMessageToLeader',
            distributedGPT__pb2.ClientMessage.SerializeToString,
            distributedGPT__pb2.LeaderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendMessageToClient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mypackage.NodeService/SendMessageToClient',
            distributedGPT__pb2.ClientMessage.SerializeToString,
            distributedGPT__pb2.ClientResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterClient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mypackage.NodeService/RegisterClient',
            distributedGPT__pb2.RegisterClientRequest.SerializeToString,
            distributedGPT__pb2.RegisterClientResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
